### ISSUE TITLE
TimeSeries doesn't work on python 3.6.4

### ISSUE THREAD

**Issue by rkhwaja** [RomelTorres/alpha_vantage#45]
`ts.get_daily('VFINX')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 173, in _format_wrapper`
`    self, *args, **kwargs)`
`  File "/usr/local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 158, in _call_wrapper`
`    return self._handle_api_call(url), data_key, meta_data_key`
`  File "/usr/local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 74, in _retry_wrapper`
`    return func(self, *args, **kwargs)`
`  File "/usr/local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 259, in _handle_api_call`
`    response = urllib.request.urlopen(url)`
`AttributeError: module 'urllib' has no attribute 'request'`

I think that you need to go back to importing urlopen directly. 1.3.6 works correctly.

**Comment by RomelTorres** [comment]
Hey @rkhwaja I am hating that urlib package. In some python versions is urlib.request.urlopen and in the other one is urlib.urlopen. I'll see if I can fix it later. 

BR Romel

**Comment by RomelTorres** [comment]
I think I will have to ditch ```urllib``` for python ```requests```, some people had some issues with the library and I reckon requests should be better. I will try to do it over the weekend.

BR
Romel

**Comment by femtotrader** [comment]
With a rewrite using [Requests](http://docs.python-requests.org/en/master/) library, you should allow to pass a `session` object like we did in https://pandas-datareader.readthedocs.io/en/latest/cache.html
so it will be possible to cache queries for a better network usage.

see https://github.com/pydata/pandas-datareader/blob/f3d754c484bcecb6e1d28859feeb446c73db283b/pandas_datareader/_utils.py#L42

and https://github.com/pydata/pandas-datareader/blob/f3d754c484bcecb6e1d28859feeb446c73db283b/pandas_datareader/base.py#L56

**Comment by RomelTorres** [comment]
Hi @rkhwaja , Can you test with the newest version?
Hi @femtotrader, I still haven't added the session handler., but will later.

BR
Romel

**Comment by Miserlou** [comment]
Please be clear and careful about caching! If I'm using this for real-time data, I definitely don't want to hit a cached endpoint!
